### ISSUE TITLE
Hint: nginx is capable of websocket reverse proxying

### ISSUE THREAD

**Issue by phaidros7** [dronus/VisSynthWeb#9]
As we talked about that:

http://nginx.org/en/docs/http/websocket.html

:)

**Comment by dronus** [comment]
Cool. I will look into this soon. 

On the other hand, WebRTC is getting more and more supported, and while it is meant to establish a peer-to-peer connection between browsers, this would be perfect for VisSynthWeb's remote control commands, thus bypassing the server entirely and replacing WebSockets for that purpose. 

However, if some realtime data should be exchanged between client and server as well (eg. future planned servers for MIDI, DMX or OSC interfaces) WebSockets would be needed again, or the server would have to act as a WebRTC peer, which is quite compicated at the moment. 

But for now, all realtime data is just relayed between the presentation and the control client by the server. So WebRTC would fit better the WebSockets I guess.

**Comment by dronus** [comment]
Sad thing is, even WebRTC requires special server elements, as the peer-to-peer connection is always initiated using a server.

**Comment by dronus** [comment]
While VisSynthWeb was updated to use WebSockets quite some while for now, just since two weeks ago I managed to configure my nginx server to proxy the VisSynthWeb server. 
The VisSynthWeb demo at https://hirnsohle.de/vissynthweb/session.html is now finally up-to-date with master, using WebSockets for realtime connection of presenter and remote control! At was on hold on an outdated pre-websocket version until now.
Thank you!
